# 1. why 파이썬? 가장 인기 있는 이유2?

## a. 판다스는? 🐼
---
- **데이터 프레임(DataFrame)을 사용해서, 데이터를 시각화, 분석할 수 있는 패키지** = R 대부분 기능과 유사
- 판다 X = 계량 경제학에서 사용하는 패널 데이터(PANner DAta) = 종단 + 횡단 데이터 = 가로세로 의미가 있는 데이터셋 처리
- 데이터를 다루기 위한 **시리즈(Series) 클래스와 데이터프레임(DataFrame) 클래스** = 데이터 사이언스에 필수 패키지
- 판다스는 느리다 X --> 넘파이에 비해서 느리다 = 넘파이 기반<br><br>

- <span style="background:yellow; color:red">**넘파이와 판다스 차이? = 넘파이 <-- 리스트 but 판다스 <-- 딕셔너리**</span>

## b. 일단 해보자. 선언! 📢
---

In [416]:
!pip install pandas
import numpy as np
import pandas as pd

Requirement already satisfied: pandas in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\tysep16\desktop\drive_t\alec\2025\강의자료\25_1_dv\.lec\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## c. 시리즈 만들기 🛤️
---
- 판다스 시리즈 = 넘파이 1차원 어레이 = 넘파이 1차원 시리즈 = 벡터와 같은 개념
- but, 판다스 시리즈 = 인덱스(index) + 값(value)

In [417]:
ps = pd.Series([90, 95, 80, 87, 85]) # 인덱스 X --> 자동정수 채우기
ps

0    90
1    95
2    80
3    87
4    85
dtype: int64

- 넘파이랑 비슷한데?

In [418]:
a1 = np.array([90, 95, 80, 87, 85]) # 넘파이 시리즈와 비교해보면?
a1

array([90, 95, 80, 87, 85])

- 차원도 비슷할 듯...

In [419]:
ps.shape, a1.shape # 차원을 보자~

((5,), (5,))

- 당연히 넘피아 기반으로 만들어 졌으니깐 당연히 넘피아 기반으로 만들어 졌으니깐

In [420]:
ps = pd.Series(range(3, 7)) # range도 가능
ps

0    3
1    4
2    5
3    6
dtype: int64

- 하지만, 판다스는 넘파이에 종단, 횡단 인덱스에 라벨 = 이름을 가지고 있어요.

In [421]:
ps = pd.Series([90, 95, 80, 87, 85], index=['a', 'b', 'c', 'd', 'e']) # 인덱스 라벨
ps

a    90
b    95
c    80
d    87
e    85
dtype: int64

In [422]:
ps.index # 인덱스 보기

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [423]:
ps.values # 벨류 보기

array([90, 95, 80, 87, 85])

In [424]:
ps.index.name = 'students' # 컬럼이 존재X = 궅이 이름 붙이자면... 
ps.name = 'math' # 컬럼이 존재X = 시리즈에 이름 붙이자면...
ps

students
a    90
b    95
c    80
d    87
e    85
Name: math, dtype: int64

- 딕셔너리로 지정 가능 = 비교 넘파이는 리스트
- 혹시나... 딕셔너리가 뭔가요?
- 참고하세요:  https://dojang.io/mod/page/view.php?id=2213

- <span style="background:yellow; color:red">**판다스 시리즈에서는 키 = 인덱스 라벨**</span>

In [425]:
dc = {'math': [90, 95, 80, 87, 85]} # 그런데 시리즈는 1차원 = 인덱스 라벨만! = 즉 인덱스 기준 <-- 주의!!
pd.Series(dc)

math    [90, 95, 80, 87, 85]
dtype: object

In [426]:
dc = {'a': 90, 'b': 95, 'c': 80, 'd': 87, 'e': 85} # 수정 방법1
pd.Series(dc, name='math')

a    90
b    95
c    80
d    87
e    85
Name: math, dtype: int64

In [427]:
dc = {'math': [90, 95, 80, 87, 85]} # 수정 방법2
pd.DataFrame(dc)

   math
0    90
1    95
2    80
3    87
4    85

## d. 시리즈 인덱싱과 슬라이싱 📇
---
- 시리즈는 기본적으로 넘파이에서 가능한 인덱싱과 슬라이싱 + 인덱스 이름(라벨)을 기반한 인덱싱과 슬라이싱

In [428]:
ps

students
a    90
b    95
c    80
d    87
e    85
Name: math, dtype: int64

- 이제껏 여기저기 기능들이 합쳐저서... 중복된 기능들 --> deprecated = 원래 데이터프레임에서도 되었지만... deprecated

In [429]:
ps[0], ps[1], ps[-1] # 곧 없어지는 방법

C:\Users\tysep16\AppData\Local\Temp\ipykernel_17096\198178904.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ps[0], ps[1], ps[-1] # 곧 없어지는 방법

(np.int64(90), np.int64(95), np.int64(85))

- <span style='background: yellow; color: red'>**다시 강조, 판다시 시리즈에서는 키값 =  인덱스 라벨 = 행(row)**</span>

In [430]:
ps['a'], ps['e'] # 당연 인덱스를 이용한 방법

(np.int64(90), np.int64(85))

In [431]:
ps[['a', 'c', 'e']] # 넘파이 기반이니 [[]] 가능하겠죠?

students
a    90
c    80
e    85
Name: math, dtype: int64

- 그렇다면 불리언 인덱싱도 가능하단 이야기...

In [432]:
ps > 85 # 불리언 시리즈

students
a     True
b     True
c    False
d     True
e    False
Name: math, dtype: bool

In [433]:
ps[ps > 85]

students
a    90
b    95
d    87
Name: math, dtype: int64

In [434]:
ps[(ps > 85) & (ps < 95)] # () AND ()

students
a    90
d    87
Name: math, dtype: int64

- 판다스 만의 특이한 접근 법 = ps.인덱스 값 = 리스트 < 넘파이 < 판다스
- 주의: <span style='background: yellow; color: red'>**다시 또 강조, 판다스 시리즈 키값 = 인덱스 라벨 = 행(row)**</span>

In [435]:
ps

students
a    90
b    95
c    80
d    87
e    85
Name: math, dtype: int64

In [436]:
ps.a, ps.d, ps.e

(np.int64(90), np.int64(87), np.int64(85))

- 이건 당연 = 판다스 시리즈에서는 컬럼이 없으므로...

In [437]:
ps.math # 시리즈에서는 키는 인덱스 라벨라고 가정했으니... 에러

AttributeError: 'Series' object has no attribute 'math'

- 당연, 슬라이싱 가능

In [438]:
ps['a':'c'] # a부터 c까지 = 주의 c 포함임!!

students
a    90
b    95
c    80
Name: math, dtype: int64

In [439]:
ps[:'d'] # 처음부터 d까지 = 주의 d 포함임!!

students
a    90
b    95
c    80
d    87
Name: math, dtype: int64

- 판다스 시리즈 객체는 인덱스 라벨으로 인덱싱 = 시리즈 값은 value로 접근 가능

In [440]:
'b' in ps # 인덱스 라벨에 b라는 학생이 있는가?

True

In [441]:
[f for f in ps] # ps value를 콜한 것

[90, 95, 80, 87, 85]

- 헷갈리네... 판다스...
- 그래서 이럴 땐... FM이 정석 like 넘파이

In [442]:
ps

students
a    90
b    95
c    80
d    87
e    85
Name: math, dtype: int64

In [443]:
[f for f in ps.index] # 인덱스 가져오기

['a', 'b', 'c', 'd', 'e']

In [444]:
[f for f in ps.values] # 이래야 인덱스 값을 본 것

[np.int64(90), np.int64(95), np.int64(80), np.int64(87), np.int64(85)]

## e. 데이터프레임 만들기 🛤️
---
- 판다스 데이터프레임 = 넘파이 2차원 어레이 = 매트릭스와 같은 개념 <-- 딕셔너리
- but, 판다스 시리즈 = 인덱스(index)/컬럼(column) + 값(value)

In [445]:
dc = {'math': [65,95,65,55,80], 'eng': [55,100,90,80,30], 'sci': [50,50,60,75,30], 'com': [40,80,30,80,100]}
df = pd.DataFrame(dc)
df

   math  eng  sci  com
0    65   55   50   40
1    95  100   50   80
2    65   90   60   30
3    55   80   75   80
4    80   30   30  100

- 인덱스 디폴트 = 0부터 시작하는 정수, 인덱스를 직접 지정 가능

In [446]:
df = pd.DataFrame(dc, index=['a', 'b', 'c', 'd', 'e'])
df

   math  eng  sci  com
a    65   55   50   40
b    95  100   50   80
c    65   90   60   30
d    55   80   75   80
e    80   30   30  100

In [447]:
df.index # 인덱스 라벨 보기

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [448]:
df.columns # 컬럼 라벨 보기

Index(['math', 'eng', 'sci', 'com'], dtype='object')

- 인덱스/컬럼 라벨 변경도 가능

In [449]:
df.index = ['a', 'b', 'c', 'd', 'f']
df

   math  eng  sci  com
a    65   55   50   40
b    95  100   50   80
c    65   90   60   30
d    55   80   75   80
f    80   30   30  100

In [450]:
df.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [451]:
df.columns = ['math', 'eng', 'sci', 'kor']
df

   math  eng  sci  kor
a    65   55   50   40
b    95  100   50   80
c    65   90   60   30
d    55   80   75   80
f    80   30   30  100

In [452]:
df.columns

Index(['math', 'eng', 'sci', 'kor'], dtype='object')

In [453]:
df.values # 데이터프레임 값보기

array([[ 65,  55,  50,  40],
       [ 95, 100,  50,  80],
       [ 65,  90,  60,  30],
       [ 55,  80,  75,  80],
       [ 80,  30,  30, 100]])

- 인덱스, 컬럼 이름을 붙이는 것도 가능

In [454]:
df.index.name = 'students'
df

          math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

In [455]:
df.columns.name = 'mid_term'
df

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

In [456]:
df.T # 트랜스포즈 = 대각화

students   a    b   c   d    f
mid_term
math      65   95  65  55   80
eng       55  100  90  80   30
sci       50   50  60  75   30
kor       40   80  30  80  100

## f. 데이터프레임 인덱싱과 슬라이싱 feat. **열방향** 📇
---
- 열 인덱싱 = 열 라벨(column label)을 키값으로 인덱싱

In [457]:
df

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

- <span style='background: yellow; color: red'>**데이터프레임에서는 키값 = 컬럼 라벨**</span>

In [458]:
df['math']

students
a    65
b    95
c    65
d    55
f    80
Name: math, dtype: int64

- !!!출력물의 클래스 타입 중요 = 차원 중요!!!

In [459]:
df['sci'] # 판다스 시리즈로 반환

students
a    50
b    50
c    60
d    75
f    30
Name: sci, dtype: int64

In [460]:
df[['sci']] # 판다스 데이터프레임로 반환

mid_term  sci
students
a          50
b          50
c          60
d          75
f          30

In [461]:
df[['math', 'eng']] # 넘파이 기반이니 [[]] 가능하겠죠?

mid_term  math  eng
students
a           65   55
b           95  100
c           65   90
d           55   80
f           80   30

- 리스트 형태로 접근 가능 --> 불리언 인덱싱 고고고

In [462]:
df['math'] > 70

students
a    False
b     True
c    False
d    False
f     True
Name: math, dtype: bool

- <span style='background: yellow; color: red'>**불리언 인덱싱으로 열의 값을 기준으로 행들을 선택한 것!!**</span>

In [463]:
df[df['math'] > 70] # 행이 선택된 것 = 중요!

mid_term  math  eng  sci  kor
students
b           95  100   50   80
f           80   30   30  100

In [464]:
df[df['math'] > 70]['math'] # 아! 데이터프레임(2차)였지 --> 시리즈(1차)

students
b    95
f    80
Name: math, dtype: int64

- <span style='background: yellow; color: red'>**데이터프레임의 강력한 인덱싱 = 키값 = 컬럼 라벨이 있으니 가능한 방법**</span>
- **단, 컬럼 라벨이 영문만 가능 + 띄어쓰기X + 특수문자X**

In [465]:
df.math

students
a    65
b    95
c    65
d    55
f    80
Name: math, dtype: int64

In [466]:
df.eng

students
a     55
b    100
c     90
d     80
f     30
Name: eng, dtype: int64

- 특이하게, 컬럼 라벨로 슬라이싱은 불가... = 헷갈려지기 시작함

In [467]:
df['math':'sci']

Empty DataFrame
Columns: [math, eng, sci, kor]
Index: []

- 넘파이 행렬식으로 인덱싱도 안돼요! = 앞에서 시리즈일때도 넘파이식 인덱싱이 deprecated...

In [468]:
df[:, 'math'] # 넘파이 행렬식으론 안돼요~

InvalidIndexError: (slice(None, None, None), 'math')

In [ ]:
df[:, 2] # 당연히 숫자 인덱싱도 불가

## g. 데이터프레임 인덱싱과 슬라이싱 feat. **행방향** 📇
---
- <span style='background: yellow; color: red'>**행 인덱싱 = 인덱스 라벨(index label)을 키값으로 슬라이싱만...**</span>

In [469]:
df

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

In [470]:
df['a'] # 행 인덱싱 = 인덱스 라벨로는 인덱싱이 불가

KeyError: 'a'

In [ ]:
df['a':'b'] # 근데 행 인덱스로 슬라이싱은 가능 --> 열괴 반대

In [471]:
df[2] # 정수 인덱싱도 불가

KeyError: 2

In [ ]:
df[:2] # 그런데? 정수 슬라이싱은 또 가능.

In [472]:
df[::2] # 스트라이딩도 가능하네..

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

- 다시 복습, 열방향으로 불리언 --> 행방향 인덱싱

In [473]:
df.math < 70

students
a     True
b    False
c     True
d     True
f    False
Name: math, dtype: bool

In [474]:
df[df.math < 70]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

- 당연히 불리언 인덱싱 가능

In [475]:
df[[True, False, True, True, False]]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

## h. 그래서, <span style='font-size: 200%; background: lime'>**아묻따! iloc**</span> 🚨
---
- 데이터프레임 열 & 행 순서를 나타내는 정수(integer)를 사용해서 열방향 & 행방향 인덱싱과 슬라이싱 = 넘파이에서 되는 것 다

- 먼저 열방향 = 넘파이에서 되는 것 모두 다

In [476]:
df.iloc[:, 0] # 그래서! iloc! integer 넘버는 가능

students
a    65
b    95
c    65
d    55
f    80
Name: math, dtype: int64

In [477]:
df.iloc[:, 0:3] # 슬라이싱도 가능하고

mid_term  math  eng  sci
students
a           65   55   50
b           95  100   50
c           65   90   60
d           55   80   75
f           80   30   30

In [478]:
df.iloc[:, -1] # 뒤에서부터도 가능하고

students
a     40
b     80
c     30
d     80
f    100
Name: kor, dtype: int64

- 리스트 속 리스트도 가능

In [479]:
df.iloc[:, [0, 3]]

mid_term  math  kor
students
a           65   40
b           95   80
c           65   30
d           55   80
f           80  100

In [480]:
df.iloc[:, [True, False, True, True]]

mid_term  math  sci  kor
students
a           65   50   40
b           95   50   80
c           65   60   30
d           55   75   80
f           80   30  100

---
# 잠깐! 컴프리헨션(comprehension) = 파이썬 문법, 이제 배워보자.

- 컴프리헨션(comprehension) = 파이썬 효율적 + 간결한 문법 = 실행문 + 반복문 + 조건문 형태
- 참조하세요.: https://wikidocs.net/138204

In [481]:
df

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

- 실행문 + 반복문 = 반복문의 인자를 하나하나 뺴서 실행문에 넣는다는 개념

In [482]:
[a + 10 for a in df.eng] # 시리즈 value에 상수 더하기

[65, 110, 100, 90, 40]

In [483]:
[f < 70 for f in df['kor']] # 시리즈에 조건문 넣기

[True, False, True, False, False]

In [484]:
df[[f < 70 for f in df['kor']]] # 불리언 인덱싱으로 데이터프레임 출력

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30

In [485]:
df[df.kor < 70] # 같은 것

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30

---

- 다시 iloc으로 돌아와서 컴프리헨션을 적용해 보자

In [486]:
df.iloc[:, [ 'a' in f for f in df.columns]] # 이건 열 선택, 컬럼에 'a'가 있는 컬럼만 선택

mid_term  math
students
a           65
b           95
c           65
d           55
f           80

- 스트라이딩도 가능

In [487]:
df.iloc[:, 0:3:2]

mid_term  math  sci
students
a           65   50
b           95   50
c           65   60
d           55   75
f           80   30

- 당연 range도 사용가능

In [488]:
df.iloc[:, range(2)]

mid_term  math  eng
students
a           65   55
b           95  100
c           65   90
d           55   80
f           80   30

- 행 방향은? = 넘파이에서 되는 것 다

In [489]:
df.iloc[0, :]

mid_term
math    65
eng     55
sci     50
kor     40
Name: a, dtype: int64

In [490]:
df.iloc[0]

mid_term
math    65
eng     55
sci     50
kor     40
Name: a, dtype: int64

In [491]:
df.iloc[[1, 3], :]

mid_term  math  eng  sci  kor
students
b           95  100   50   80
d           55   80   75   80

In [492]:
df.iloc[[1, 3]]

mid_term  math  eng  sci  kor
students
b           95  100   50   80
d           55   80   75   80

In [493]:
df.iloc[[True, False, True, False, True], :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

In [494]:
df.iloc[[True, False, True, False, True]]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

In [495]:
[f < 70 for f in df['kor']] # 다시한번 강조 --> 이번이 3번째... 그만큼 중요

[True, False, True, False, False]

In [496]:
df.iloc[[f < 70 for f in df['kor']], :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30

In [497]:
df.iloc[[f < 70 for f in df['kor']]] # 같은 것

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30

In [498]:
df.iloc[df.kor < 70] # --> 이게 왜? 불리언 인덱싱 되면서? 오락가락...

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [499]:
df[df.kor < 70] # 이건 되면서

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30

In [500]:
df.iloc[range(2), :] # 물론 range 됩니다.

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80

In [501]:
df.iloc[range(2)]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80

## i. 또한, <span style='font-size: 200%; background: pink'>**아묻따!아묻따! loc**</span> 🚨
---
- 데이터프레임 열 & 행 순서를 나타내는 라벨을 사용해서 열방향 & 행방향 인덱싱과 슬라이싱

- 먼저 열방향

In [502]:
df

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

- 결국, iloc이 가능한 것들 다 가능, integer --> 라벨

In [503]:
df.loc[:, 'eng']

students
a     55
b    100
c     90
d     80
f     30
Name: eng, dtype: int64

In [504]:
df.loc[:, 'math':'sci'] # 슬라이싱 가능

mid_term  math  eng  sci
students
a           65   55   50
b           95  100   50
c           65   90   60
d           55   80   75
f           80   30   30

In [505]:
df.loc[:, 'math'::2] # 스트라이딩도 가능

mid_term  math  sci
students
a           65   50
b           95   50
c           65   60
d           55   75
f           80   30

In [506]:
df.loc[:, ['eng', 'sci']] # 리스트를 이용한 복수 선택도 가능

mid_term  eng  sci
students
a          55   50
b         100   50
c          90   60
d          80   75
f          30   30

In [507]:
df.loc[:, [True, False, True, False]] # 당연히 불리언 인덱싱도 가능

mid_term  math  sci
students
a           65   50
b           95   50
c           65   60
d           55   75
f           80   30

In [508]:
df.loc[:, ['a' in cn or 's' in cn for cn in df.columns]] # 그래서 컨프리헨션도 가능!

mid_term  math  sci
students
a           65   50
b           95   50
c           65   60
d           55   75
f           80   30

- 다음 행방향

In [509]:
df.loc['a', :]

mid_term
math    65
eng     55
sci     50
kor     40
Name: a, dtype: int64

In [510]:
df.loc['a']

mid_term
math    65
eng     55
sci     50
kor     40
Name: a, dtype: int64

In [511]:
df.loc[['a', 'c', 'f'], :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

In [512]:
df.loc[['a', 'c', 'f']] # 물론 생략가능

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

In [513]:
df.loc['a':'c'] # 슬라이싱 가능

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30

In [514]:
df.loc['a'::2] # 스트라이딩 가능

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
f           80   30   30  100

- 컴프리헨션은 너무 많이 했으니...

In [515]:
df.loc[df.math < 70, :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

In [516]:
df.loc[df.math < 70]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

In [517]:
df.loc[[f < 70 for f in df.math], :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

In [518]:
df.loc[[f < 70 for f in df.math]]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

## j. 요약 🔛
---
- 판다스 시리즈에서 키는 인덱스
- 판다스 데이터프레임에서 키는 컬럼
 
- df['문자'] = df.'문자' = 컬럼선택 but 슬라이딩 안됨
- df['문자':'문자'] = 로우선택 but 단일문자 인덱싱 안됨

- 불리언인덱싱은 로우컬럼 다가능 = 컨프리헨션

- 로우선택시 .iloc[] = .iloc[, :] --> 후자 추천
- 로우선택시 .loc[] = .loc[, :] --> 후자 추천

- <span style='background:yellow; color:red'>**열 --> columns**</span>
  
|     type of indexer      |  .  |  []  |  .iloc  |   .loc   | 추천 | 
|:-------------------------|:---:|:----:|:-------:|:--------:|:-------:|
|           int            |  X  |  X   |    O    |    X     | iloc 쓰세요 |
|         int:int          |  X  |  X   |    O    |    X     | iloc 쓰세요 |
|        [int,int]         |  X  |  X   |    O    |    X     | iloc 쓰세요 | 
|           str            |  O  |  O   |    X    |    O     | . 혹은 [] 혹은 loc | 
|         str:str          |  X  |  X   |    X    |    O     | loc 쓰세요 | 
|        [str,str]         |  X  |  O   |    X    |    O     | loc 쓰세요 |
|       [bool,bool]        |  X  |  X   |    O    |    O     | loc 쓰세요 | 

- <span style='background:yellow; color:red'>**행 --> rows**</span>

|     type of indexer      |  .  |  []  |  .iloc  |   .loc   | 내가 쓴다면? | 
|:-------------------------|:---:|:----:|:-------:|:--------:|:-------:|
|           int            |  X  |  X   |    O    |    X     | iloc 쓰세요 | 
|         int:int          |  X  |  O   |    O    |    X     | iloc 쓰세요 |
|        [int,int]         |  X  |  X   |    O    |    X     | iloc 쓰세요 | 
|           str            |  X  |  X   |    X    |    O     | loc 쓰세요  |
|         str:str          |  X  |  O   |    X    |    O     | loc 쓰세요  |
|        [str,str]         |  X  |  X   |    X    |    O     | loc 쓰세요  | 
|       [bool,bool]        |  X  |  O   |    O    |    O     | loc 쓰세요  |

## l. 그냥 이거 쓰세요. 🤩
---
- 가장 추천 --> 가장 안전 but 타자 많음

In [519]:
df.loc[:, :]

mid_term  math  eng  sci  kor
students
a           65   55   50   40
b           95  100   50   80
c           65   90   60   30
d           55   80   75   80
f           80   30   30  100

- 특별한 상황 1. and 2. = 열을 뽑을 때

In [520]:
df.math # 특별예외 1

students
a    65
b    95
c    65
d    55
f    80
Name: math, dtype: int64

In [521]:
df['math'] # 특별예외 2

students
a    65
b    95
c    65
d    55
f    80
Name: math, dtype: int64

### - 특별한 상황 3. = 행을 뽑을 때

In [522]:
df[df.math < 70] # 특정 열을 기준으로 조건을 만족시키는 행을 뽑을 때... 특별예외 3

mid_term  math  eng  sci  kor
students
a           65   55   50   40
c           65   90   60   30
d           55   80   75   80

# 2. 인생은 실전이야.

## a. 준비 = 파일 읽어오기 👌
---
- url에서 직접 받아오기

In [523]:
df = pd.read_csv('https://raw.githubusercontent.com/tysep16/DV25_1/refs/heads/main/movie.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- (터미널로 다운받아서...) 파일에서 불러오기

In [524]:
df = pd.read_csv('./data/movie.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- 인덱스/컬럼 라벨 출력

In [525]:
df.index

RangeIndex(start=0, stop=4916, step=1)

In [526]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

- 상위 10개만 출력, 하위 10개만 출력

In [527]:
df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,46055,Kirsten Dunst,0.0,sandman|spider man|symbiote|venom|villain,http://www.imdb.com/title/tt0413300/?ref_=fn_t...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,2036,M.C. Gainey,1.0,17th century|based on fairy tale|disney|flower...,http://www.imdb.com/title/tt0398286/?ref_=fn_t...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,92000,Scarlett Johansson,4.0,artificial intelligence|based on comic book|ca...,http://www.imdb.com/title/tt2395427/?ref_=fn_t...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,58753,Rupert Grint,3.0,blood|book|love|potion|professor,http://www.imdb.com/title/tt0417741/?ref_=fn_t...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [528]:
df.tail(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,Ian Gamazon,Cavite,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,147,Consuelo Gómez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,Richard Jewell,The Mongol King,36,93,Sara Stepnicka,0.0,jewell|mongol|nostradamus|stepnicka|vallone,http://www.imdb.com/title/tt0430371/?ref_=fn_t...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- 옵션 변경 --> 꼼수

In [529]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [530]:
pd.options.display.min_rows = 30
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,46055,Kirsten Dunst,0.0,sandman|spider man|symbiote|venom|villain,http://www.imdb.com/title/tt0413300/?ref_=fn_t...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,2036,M.C. Gainey,1.0,17th century|based on fairy tale|disney|flower...,http://www.imdb.com/title/tt0398286/?ref_=fn_t...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,92000,Scarlett Johansson,4.0,artificial intelligence|based on comic book|ca...,http://www.imdb.com/title/tt2395427/?ref_=fn_t...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,58753,Rupert Grint,3.0,blood|book|love|potion|professor,http://www.imdb.com/title/tt0417741/?ref_=fn_t...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,24450,Alan D. Purwin,0.0,based on comic book|batman|sequel to a reboot|...,http://www.imdb.com/title/tt2975590/?ref_=fn_t...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,29991,Frank Langella,0.0,crystal|epic|lex luthor|lois lane|return to earth,http://www.imdb.com/title/tt0348150/?ref_=fn_t...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,2023,Rory Kinnear,1.0,action hero|attempted rape|bond girl|official ...,http://www.imdb.com/title/tt0830515/?ref_=fn_t...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,48486,Jack Davenport,2.0,box office hit|giant squid|heart|liar's dice|m...,http://www.imdb.com/title/tt0383574/?ref_=fn_t...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,45757,Tom Wilkinson,1.0,horse|outlaw|texas|texas ranger|train,http://www.imdb.com/title/tt1210819/?ref_=fn_t...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4901,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,Patrick O'Donnell,Tin Can Man,57,15,Emma Eliza Regan,0.0,NaN,http://www.imdb.com/title/tt1235811/?ref_=fn_t...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
4902,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,Kôji Yakusho,The Cure,6318,115,Denden,0.0,breasts|interrogation|investigation|murder|wat...,http://www.imdb.com/title/tt0123948/?ref_=fn_t...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
4903,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,Tatiana Suarez-Pico,On the Downlow,156,62,Eric Ambriz,2.0,gang initiation|gunplay|hazing|latino|shakespe...,http://www.imdb.com/title/tt0390323/?ref_=fn_t...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
4904,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,Julianna Pitt,Sanctuary; Quite a Conundrum,133,1111,John Lucas,NaN,nudity|party|pirate|swimsuit|three word title,http://www.imdb.com/title/tt2049518/?ref_=fn_t...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
4905,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,Peter Greene,Bang,438,1186,James Noble,1.0,corruption|homeless|homeless man|motorcycle|ur...,http://www.imdb.com/title/tt0109266/?ref_=fn_t...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,Ian Gamazon,Cavite,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,147,Consuelo Gómez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,Richard Jewell,The Mongol King,36,93,Sara Stepnicka,0.0,jewell|mongol|nostradamus|stepnicka|vallone,http://www.imdb.com/title/tt0430371/?ref_=fn_t...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [531]:
df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,...,4896,4897,4898,4899,4900,4901,4902,4903,4904,4905,4906,4907,4908,4909,4910,4911,4912,4913,4914,4915
color,Color,Color,Color,Color,NaN,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,...,Color,Color,Color,Color,Color,Black and White,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color,Color
director_name,James Cameron,Gore Verbinski,Sam Mendes,Christopher Nolan,Doug Walker,Andrew Stanton,Sam Raimi,Nathan Greno,Joss Whedon,David Yates,Zack Snyder,Bryan Singer,Marc Forster,Gore Verbinski,Gore Verbinski,Zack Snyder,Andrew Adamson,Joss Whedon,Rob Marshall,Barry Sonnenfeld,...,Daryl Wein,Jason Trost,John Waters,Olivier Assayas,Jafar Panahi,Ivan Kavanagh,Kiyoshi Kurosawa,Tadeo Garcia,Thomas L. Phillips,Ash Baron-Cohen,Shane Carruth,Neill Dela Llana,Robert Rodriguez,Anthony Vallone,Edward Burns,Scott Smith,NaN,Benjamin Roberds,Daniel Hsia,Jon Gunn
num_critic_for_reviews,723.0,302.0,602.0,813.0,NaN,462.0,392.0,324.0,635.0,375.0,673.0,434.0,403.0,313.0,450.0,733.0,258.0,703.0,448.0,451.0,...,22.0,42.0,73.0,81.0,64.0,12.0,78.0,NaN,13.0,10.0,143.0,35.0,56.0,NaN,14.0,1.0,43.0,13.0,14.0,43.0
duration,178.0,169.0,148.0,164.0,NaN,132.0,156.0,100.0,141.0,153.0,183.0,169.0,106.0,151.0,150.0,143.0,150.0,173.0,136.0,106.0,...,88.0,78.0,108.0,110.0,90.0,83.0,111.0,84.0,82.0,98.0,77.0,80.0,81.0,84.0,95.0,87.0,43.0,76.0,100.0,90.0
director_facebook_likes,0.0,563.0,0.0,22000.0,131.0,475.0,0.0,15.0,0.0,282.0,0.0,0.0,395.0,563.0,563.0,0.0,80.0,0.0,252.0,188.0,...,38.0,91.0,0.0,107.0,397.0,18.0,62.0,5.0,120.0,3.0,291.0,0.0,0.0,2.0,0.0,2.0,NaN,0.0,0.0,16.0
actor_3_facebook_likes,855.0,1000.0,161.0,23000.0,NaN,530.0,4000.0,284.0,19000.0,10000.0,2000.0,903.0,393.0,1000.0,1000.0,748.0,201.0,19000.0,1000.0,718.0,...,211.0,86.0,105.0,45.0,0.0,0.0,6.0,12.0,84.0,152.0,8.0,0.0,6.0,2.0,133.0,318.0,319.0,0.0,489.0,16.0
actor_2_name,Joel David Moore,Orlando Bloom,Rory Kinnear,Christian Bale,Rob Walker,Samantha Morton,James Franco,Donna Murphy,Robert Downey Jr.,Daniel Radcliffe,Lauren Cohan,Marlon Brando,Mathieu Amalric,Orlando Bloom,Ruth Wilson,Christopher Meloni,Pierfrancesco Favino,Robert Downey Jr.,Sam Claflin,Michael Stuhlbarg,...,Heather Burns,Jason Trost,Mink Stole,Béatrice Dalle,Nargess Mamizadeh,Michael Parle,Anna Nakagawa,Michael Cortez,Joe Coffey,Stanley B. Herman,David Sullivan,Edgar Tancangco,Peter Marquardt,John Considine,Caitlin FitzGerald,Daphne Zuniga,Valorie Curry,Maxwell Moody,Daniel Henney,Brian Herzlinger
actor_1_facebook_likes,1000.0,40000.0,11000.0,27000.0,131.0,640.0,24000.0,799.0,26000.0,25000.0,15000.0,18000.0,451.0,40000.0,40000.0,15000.0,22000.0,26000.0,40000.0,10000.0,...,331.0,407.0,462.0,576.0,5.0,10.0,89.0,21.0,785.0,789.0,291.0,0.0,121.0,45.0,296.0,637.0,841.0,0.0,946.0,86.0
gross,760505847.0,309404152.0,200074175.0,448130642.0,NaN,73058679.0,336530303.0,200807262.0,458991599.0,301956980.0,330249062.0,200069408.0,168368427.0,423032628.0,89289910.0,291021565.0,141614023.0,623279547.0,241063875.0,179020854.0,...,76382.0,NaN,180483.0,136007.0,673780.0,NaN,94596.0,NaN,NaN,NaN,424760.0,70071.0,2040920.0,NaN,4584.0,NaN,NaN,NaN,10443.0,85222.0
genres,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Fantasy,Action|Adventure|Thriller,Action|Thriller,Documentary,Action|Adventure|Sci-Fi,Action|Adventure|Romance,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Action|Adventure|Sci-Fi,Adventure|Family|Fantasy|Mystery,Action|Adventure|Sci-Fi,Action|Adventure|Sci-Fi,Action|Adventure,Action|Adventure|Fantasy,Action|Adventure|Western,Action|Adventure|Fantasy|Sci-Fi,Action|Adventure|Family|Fantasy,Action|Adventure|Sci-Fi,Action|Adventure|Fantasy,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,Romance,Sci-Fi|Thriller,Comedy|Crime|Horror,Drama|Music|Romance,Drama,Horror,Crime|Horror|Mystery|Thriller,Drama,Comedy|Horror|Thriller,Crime|Drama,Drama|Sci-Fi|Thriller,Thriller,Action|Crime|Drama|Romance|Thriller,Crime|Drama,Comedy|Drama,Comedy|Drama,Crime|Drama|Mystery|Thriller,Drama|Horror|Thriller,Comedy|Drama|Romance,Documentary
actor_1_name,CCH Pounder,Johnny Depp,Christoph Waltz,Tom Hardy,Doug Walker,Daryl Sabara,J.K. Simmons,Brad Garrett,Chris Hemsworth,Alan Rickman,Henry Cavill,Kevin Spacey,Giancarlo Giannini,Johnny Depp,Johnny Depp,Henry Cavill,Peter Dinklage,Chris Hemsworth,Johnny Depp,Will Smith,...,Zoe Lister-Jones,Sean Whalen,Divine,Maggie Cheung,Fereshteh Sadre Orafaiy,Patrick O'Donnell,Kôji Yakusho,Tatiana Suarez-Pico,Julianna Pitt,Peter Greene,Shane Carruth,Ian Gamazon,Carlos Gallardo,Richard Jewell,Kerry Bishé,Eric Mabius,Natalie Zea,Eva Boehnke,Alan Ruck,John August
movie_title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,Star Wars: Episode VII - The Force Awakens,John Carter,Spider-Man 3,Tangled,Avengers: Age of Ultron,Harry Potter and the Half-Blood Prince,Batman v Superman: Dawn of Justice,Superman Returns,Quantum of Solace,Pirates of the Caribbean: Dead Man's Chest,The Lone Ranger,Man of Steel,The Chronicles of Narnia: Prince Caspian,The Avengers,Pirates of the Caribbean: On Stranger Tides,Men in Black 3,...,Breaking Upwards,All Superheroes Must Die,Pink Flamingos,Clean,The Circle,Tin Can Man,The Cure,On the Downlow,Sanctuary; Quite a Conundrum,Bang,Primer,Cavite,El Mariachi,The Mongol King,Newlyweds,Signed Sealed Delivered,The Following,A Plague So Pleasant,Shanghai Calling,My Date with Drew
num_voted_users,886204,471220,275868,1144337,8,212204,383056,294810,462669,321795,371639,240396,330784,522040,181792,548573,149922,995415,370704,268154,...,1194,1771,16792,3924,4555,57,6318,156,133,438,72639,589,52055,36,1338,629,73839,38,1255,4285
cast_total_facebook_likes,4834,48350,11700,106759,143,1873,46055,2036,92000,58753,24450,29991,2023,48486,45757,20495,22697,87697,54083,12572,...,1546,674,760,776,5,15,115,62,1111,1186,368,0,147,93,690,2283,1753,0,2386,163
actor_3_name,Wes Studi,Jack Davenport,Stephanie Sigman,Joseph Gordon-Levitt,NaN,Polly Walker,Kirsten Dunst,M.C. Gainey,Scarlett Johansson,Rupert Grint,Alan D. Purwin,Frank Langella,Rory Kinnear,Jack Davenport,Tom Wilkinson,Harry Lennix,Damián Alcázar,Scarlett Johansson,Stephen Graham,Nicole Scherzinger,...,Ebon Moss-Bachrach,Nick Principe,Edith Massey,Don McKellar,Mojgan Faramarzi,Emma Eliza Regan,Denden,Eric Ambriz,John Lucas,James Noble,Casey Gooden,Quynn Ton,Consuelo Gómez,Sara Stepnicka,Daniella Pineda,Crystal Lowe,Sam Underwood,David Chandler,Eliza Coupe,Jon Gunn
facenumber_in_poster,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,4.0,3.0,0.0,0.0,1.0,2.0,1.0,0.0,4.0,3.0,4.0,1.0,...,2.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,5.0,0.0
plot_keywords,avatar|future|marine|native|paraplegic,goddess|marriage ceremony|marriage proposal|pi...,bomb|espionage|sequel|spy|terrorist,deception|imprisonment|lawlessness|police offi...,NaN,alien|american civil war|male nipple|mars|prin...,sandman|spider man|symbiote|venom|villain,17th century|based on fairy tale|disney|flower...,artificial intelligence|based on comic book|ca...,blood|book|love|potion|professor,based on comic book|batman|sequel to a reboot|...,crystal|epic|lex luthor|lois lane|return to earth,action hero|attempted rape|bond girl|official ...,box office hit|giant squid|heart|liar's dice|m...,horse|outlaw|texas|texas ranger|train,based on comic book|british actor playing amer...,brother brother relationship|brother sister re...,alien invasion|assassin|battle|iron man|soldier,blackbeard|captain|pirate|revenge|soldier,alien|criminal|m.i.b.|maximum security prison|...,...,NaN,arch villain|game of death|kidnapping|superhero,absurd humor|egg|gross out humor|lesbian|sex,jail|junkie|money|motel|singer,abortion|bus|hospital|prison|prostitution,NaN,breasts|interrogation|investigation|murder|wat...,gang initiation|gunplay|hazing|latino|shakespe...,nudity|party|pirate|swimsuit|three word title,corruption|homeless|homeless man|motorcycle|ur...,changing the future|independent film|invention...,jihad|mindanao|philippines|security guard|squa...,assassin|death|guitar|gun|mariachi,jewell|mongol|nostradamus|stepnicka|vallone,written and directed by cast member,fraud|postal worker|prison|theft|trial,cult|fbi|hideout|prison escape|serial killer,NaN,NaN,actress name in title|crush|date|four word tit...
movie_imdb_link,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,http://www.imdb.com/title/tt0413300/?ref_=fn_t...,http://www.imdb.com/title/tt0398286/?ref_=fn_t...,http://www.imdb.com/title/tt2395427/?ref_=fn_t...,http://www.imdb.com/title/tt0417741/?ref_=fn_t...,http://www.imdb.com/title/tt2975590/?ref_=fn_t...,http://www.imdb.com/title/tt0348150/?ref_=fn_t...,http://www.imdb.com/title/tt0830515/?ref_=fn_t...,http://www.imdb.com/title/tt0383574/?ref_=fn_t...,http://www.imdb.com/title/tt1210819/?ref_=fn_t...,http://www.imdb.com/title/tt0770828/?ref_=fn_t...,http://www.imdb.com/title/tt0499448/?ref_=fn_t...,http://www.imdb.com/title/tt0848228/?ref_=fn_t...,http://www.imdb.com/title/tt1298650/?ref_=fn_t...,http://www.imdb.com/title/tt1409024/?ref_=fn_t...,...,http://www.imdb.com/title/tt1247644/?ref_=fn_t...,http://www.imdb.com/title/tt1836212/?ref_=fn_t...,http://www.imdb.com/title/tt0069089/?ref_=fn_t...,http://www.imdb.com/title/tt0388838/?ref_=fn_t...,http://www.imdb.com/title/tt0255094/?ref_=fn_t...,http://www.imdb.com/title/tt1235811/?ref_=fn_t...,http://www.imdb.com/title/tt0123948/?ref_=fn_t...,http://www.imdb.com/title/tt0390323/?ref_=fn_t...,http://www.imdb.com/title/tt2049518/?ref_=fn_t...,http://www.imdb.com/title/tt0109266/?ref_=fn_t...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,http://www.imdb.com/title/tt0430371/?ref_=fn_t...,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...
num_user_for_reviews,3054.0,1238.0,994.0,2701.0,NaN,738.0,1902.0,387.0,1117.0,973.0,3018.0,2367.0,1243.0,1832.0,711.0,2536.0,438.0,1722.0,484.0,341.0,...,8.0,35.0,183.0,39.0,26.0,1.0,50.0,3.0,8.0,14.0,371.0,35.0,130.0,1.0,14.0,6.0,359.0,3.0,9.0,84.0
language,English,English,English,English,NaN,English,English,English,English,English,English,English,English,English,English,English,English,English,English,English,...,English,English,English,French,Persian,English,Japanese,English,English,English,English,English,Spanish,English,English,English,English,English,English,English
country,USA,USA,UK,USA,NaN,USA,USA,USA,USA,UK,USA,USA,UK,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,France,Iran,Ireland,Japan,USA,USA,USA,USA,Philippines,USA,USA,USA,Canada,USA,USA,USA,USA
content_rating,PG-13,PG-13,PG-13,PG-13,NaN,PG-13,PG-13,PG,PG-13,PG,PG-13,PG-13,PG-13,PG-13,PG-13,PG-13,PG,PG-13,PG-13,PG-13,...,NaN,Unrated,NC-17,R,Not Rated,NaN,NaN,NaN,NaN,NaN,PG-13,Not Rated,R,PG-13,Not Rated,NaN,TV-14,NaN,PG-13,PG
budget,237000000.0,300000000.0,245000000.0,250000000.0,NaN,263700000.0,258000000.0,260000000.0,250000000.0,250000000.0,250000000.0,209000000.0,200000000.0,225000000.0,215000000.0,225000000.0,225000000.0,220000000.0,250000000.0,225000000.0,...,15000.0,20000.0,10000.0,4500.0,10000.0,10000.0,1000000.0,NaN,200000.0,NaN,7000.0,7000.0,7000.0,3250.0,9000.0,NaN,NaN,1400.0,NaN,1100.0
title_year,2009.0,2007.0,2015.0,2012.0,NaN,2012.0,2007.0,2010.0,2015.0,2009.0,2016.0,2006.0,2008.0,2006.0,2013.0,2013.0,2008.0,2012.0,2011.0,2012.0,...,2009.0,2011.0,1972.0,2004.0,2000.0,2007.0,1997.0,2004.0,2012.0,1995.0,2004.0,2005.0,1992.0,2005.0,2011.0,2013.0,NaN,2013.0,2012.0,2004.0
actor_2_facebook_likes,936.0,5000.0,393.0,23000.0,12.0,632.0,11000.0,553.0,21000.0,11000.0,4000.0,10000.0,412.0,5000.0,2000.0,3000.0,216.0,21000.0,11000.0,816.0,...,212.0,91.0,143.0,133.0,0.0,5.0,13.0,20.0,98.0,194.0,45.0,0.0,20.0,44.0,205.0,470.0,593.0,0.0,719.0,23.0
imdb_score,7.9,7.1,6.8,8.5,7.1,6.6,6.2,7.8,7.5,7.5,6.9,6.1,6.7,7.3,6.5,7.2,6.6,8.1,6.7,6.8,...,6.2,4.0,6.1,6.9,7.5,6.7,7.4,6.1,5.4,6.4,7.0,6.3,6.9,7.8,6.4,7.7,7.5,6.3,6.3,6.6
aspect_ratio,1.78,2.35,2.35,2.35,NaN,2.35,2.35,1.85,2.35,2.35,2.35,2.35,2.35,2.35,2.35,2.35,2.35,1.85,2.35,1.85,...,2.35,2.35,1.37,2.35,1.85,1.33,1.85,NaN,16.0,NaN,1.85,NaN,1.37,NaN,NaN,NaN,16.0,NaN,2.35,1.85
movie_facebook_likes,33000,0,85000,164000,0,24000,0,29000,118000,10000,197000,0,0,5000,48000,118000,0,123000,58000,40000,...,324,835,0,171,697,105,817,22,424,20,19000,74,0,4,413,84,32000,16,660,456

In [532]:
pd.options.display.min_rows = 10
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [533]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [534]:
df.director_name # 감독 이름만 출력

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [535]:
df[['genres', 'movie_title', 'imdb_score', 'movie_facebook_likes']] # 원하는 컬럼 모아서 출력

,genres,movie_title,imdb_score,movie_facebook_likes
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,7.9,33000
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,7.1,0
2,Action|Adventure|Thriller,Spectre,6.8,85000
3,Action|Thriller,The Dark Knight Rises,8.5,164000
4,Documentary,Star Wars: Episode VII - The Force Awakens,7.1,0
...,...,...,...,...
4911,Comedy|Drama,Signed Sealed Delivered,7.7,84
4912,Crime|Drama|Mystery|Thriller,The Following,7.5,32000
4913,Drama|Horror|Thriller,A Plague So Pleasant,6.3,16
4914,Comedy|Drama|Romance,Shanghai Calling,6.3,660
4915,Documentary,My Date with Drew,6.6,456

In [536]:
df[['movie_title', 'genres', 'movie_facebook_likes', 'imdb_score']] # 순서도 정할 수 있음 = 방법 1

,movie_title,genres,movie_facebook_likes,imdb_score
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,33000,7.9
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,0,7.1
2,Spectre,Action|Adventure|Thriller,85000,6.8
3,The Dark Knight Rises,Action|Thriller,164000,8.5
4,Star Wars: Episode VII - The Force Awakens,Documentary,0,7.1
...,...,...,...,...
4911,Signed Sealed Delivered,Comedy|Drama,84,7.7
4912,The Following,Crime|Drama|Mystery|Thriller,32000,7.5
4913,A Plague So Pleasant,Drama|Horror|Thriller,16,6.3
4914,Shanghai Calling,Comedy|Drama|Romance,660,6.3
4915,My Date with Drew,Documentary,456,6.6

In [537]:
df.loc[:, ['movie_title', 'genres', 'movie_facebook_likes', 'imdb_score']] # 순서도 정할 수 있음

,movie_title,genres,movie_facebook_likes,imdb_score
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,33000,7.9
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,0,7.1
2,Spectre,Action|Adventure|Thriller,85000,6.8
3,The Dark Knight Rises,Action|Thriller,164000,8.5
4,Star Wars: Episode VII - The Force Awakens,Documentary,0,7.1
...,...,...,...,...
4911,Signed Sealed Delivered,Comedy|Drama,84,7.7
4912,The Following,Crime|Drama|Mystery|Thriller,32000,7.5
4913,A Plague So Pleasant,Drama|Horror|Thriller,16,6.3
4914,Shanghai Calling,Comedy|Drama|Romance,660,6.3
4915,My Date with Drew,Documentary,456,6.6

In [538]:
df.loc[:, ['facebook' in f for f in df.columns]] # 컨프리헨션으로 원하는 열을 선택

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456

In [541]:
df.loc[df.imdb_score > 9.0, :]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,Martin Short,Towering Inferno,10,1125,Joe Flaherty,2.0,NaN,http://www.imdb.com/title/tt0691996/?ref_=fn_t...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,25,Olgierd Lukaszewicz,0.0,meaning of life|moral challenge|morality|searc...,http://www.imdb.com/title/tt0092337/?ref_=fn_t...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,261818,Sam Medina,5.0,NaN,http://www.imdb.com/title/tt3082898/?ref_=fn_t...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0

In [542]:
df.loc[df.imdb_score > 9.0]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,Martin Short,Towering Inferno,10,1125,Joe Flaherty,2.0,NaN,http://www.imdb.com/title/tt0691996/?ref_=fn_t...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,25,Olgierd Lukaszewicz,0.0,meaning of life|moral challenge|morality|searc...,http://www.imdb.com/title/tt0092337/?ref_=fn_t...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,261818,Sam Medina,5.0,NaN,http://www.imdb.com/title/tt3082898/?ref_=fn_t...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0

In [540]:
df[df.imdb_score > 9.0]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,Martin Short,Towering Inferno,10,1125,Joe Flaherty,2.0,NaN,http://www.imdb.com/title/tt0691996/?ref_=fn_t...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,25,Olgierd Lukaszewicz,0.0,meaning of life|moral challenge|morality|searc...,http://www.imdb.com/title/tt0092337/?ref_=fn_t...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,261818,Sam Medina,5.0,NaN,http://www.imdb.com/title/tt3082898/?ref_=fn_t...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0

In [543]:
df.loc[[f > 9 for f in df.imdb_score], :]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,Martin Short,Towering Inferno,10,1125,Joe Flaherty,2.0,NaN,http://www.imdb.com/title/tt0691996/?ref_=fn_t...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,25,Olgierd Lukaszewicz,0.0,meaning of life|moral challenge|morality|searc...,http://www.imdb.com/title/tt0092337/?ref_=fn_t...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,261818,Sam Medina,5.0,NaN,http://www.imdb.com/title/tt3082898/?ref_=fn_t...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0

In [544]:
df.loc[[f > 9 for f in df.imdb_score]]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,Martin Short,Towering Inferno,10,1125,Joe Flaherty,2.0,NaN,http://www.imdb.com/title/tt0691996/?ref_=fn_t...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,25,Olgierd Lukaszewicz,0.0,meaning of life|moral challenge|morality|searc...,http://www.imdb.com/title/tt0092337/?ref_=fn_t...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,261818,Sam Medina,5.0,NaN,http://www.imdb.com/title/tt3082898/?ref_=fn_t...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0

In [539]:
df.iloc[:100:5]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,24450,Alan D. Purwin,0.0,based on comic book|batman|sequel to a reboot|...,http://www.imdb.com/title/tt2975590/?ref_=fn_t...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,20495,Harry Lennix,0.0,based on comic book|british actor playing amer...,http://www.imdb.com/title/tt0770828/?ref_=fn_t...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,9152,James Nesbitt,0.0,army|elf|hobbit|middle earth|orc,http://www.imdb.com/title/tt2310332/?ref_=fn_t...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,7123,Evan Parke,0.0,animal name in title|ape abducts a woman|goril...,http://www.imdb.com/title/tt0360717/?ref_=fn_t...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
30,Color,Sam Mendes,750.0,143.0,0.0,393.0,Helen McCrory,883.0,304360277.0,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,2039,Rory Kinnear,0.0,brawl|childhood home|computer cracker|intellig...,http://www.imdb.com/title/tt1074638/?ref_=fn_t...,1498.0,English,UK,PG-13,200000000.0,2012.0,563.0,7.8,2.35,80000
35,Color,Dan Scanlon,376.0,104.0,37.0,760.0,Tyler Labine,12000.0,268488329.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,Monsters University,235025,14863,Sean Hayes,0.0,cheating|fraternity|monster|singing in a car|u...,http://www.imdb.com/title/tt1453405/?ref_=fn_t...,265.0,English,USA,G,200000000.0,2013.0,779.0,7.3,1.85,44000
40,Color,Joseph Kosinski,469.0,125.0,364.0,1000.0,Olivia Wilde,12000.0,172051787.0,Action|Adventure|Sci-Fi,Jeff Bridges,TRON: Legacy,264183,25550,James Frain,0.0,arcade|bridge|disappearance|escape|warrior,http://www.imdb.com/title/tt1104001/?ref_=fn_t...,665.0,English,USA,PG,170000000.0,2010.0,10000.0,6.8,2.35,30000
45,Color,James Wan,424.0,140.0,0.0,14000.0,Paul Walker,26000.0,350034110.0,Action|Crime|Thriller,Jason Statham,Furious 7,278232,79150,Vin Diesel,0.0,car falling off a cliff|hospital|revenge|star ...,http://www.imdb.com/title/tt2820852/?ref_=fn_t...,657.0,English,USA,PG-13,190000000.0,2015.0,23000.0,7.2,2.35,94000
50,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,29770,Steve Bisley,4.0,ingratitude|mansion|party|title appears in wri...,http://www.imdb.com/title/tt1343092/?ref_=fn_t...,753.0,English,Australia,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000
55,Color,Peter Sohn,298.0,93.0,113.0,113.0,Jack McGraw,275.0,123070338.0,Adventure|Animation|Comedy|Family|Fantasy,A.J. Buckley,The Good Dinosaur,62836,696,Peter Sohn,0.0,apatosaurus|asteroid|dinosaur|fear|river,http://www.imdb.com/title/tt1979388/?ref_=fn_t...,345.0,English,USA,PG,NaN,2015.0,150.0,6.8,2.35,20000
60,Color,Roland Emmerich,367.0,158.0,776.0,310.0,Liam James,1000.0,166112167.0,Action|Adventure|Sci-Fi,Oliver Platt,2012,283418,2144,Tom McCarthy,0.0,ark|catastrophe|geologist|president|writer,http://www.imdb.com/title/tt1190080/?ref_=fn_t...,1055.0,English,USA,PG-13,200000000.0,2009.0,468.0,5.8,2.35,13000
65,Color,Bryan Singer,396.0,144.0,0.0,1000.0,Michael Fassbender,34000.0,154985087.0,Action|Adventure|Sci-Fi,Jennifer Lawrence,X-Men: Apocalypse,148379,49684,Tye Sheridan,6.0,mutant|superhero|superhero team|x men|year 1983,http://www.imdb.com/title/tt3385516/?ref_=fn_t...,622.0,English,USA,PG-13,178000000.0,2016.0,13000.0,7.3,2.35,54000
70,Color,Martin Scorsese,682.0,126.0,17000.0,1000.0,Christopher Lee,17000.0,73820094.0,Adventure|Drama|Family|Mystery,Chloë Grace Moretz,Hugo,245333,36017,Ray Winstone,0.0,automaton|mechanical|railway station|steampunk...,http://www.imdb.com/title/tt0970179/?ref_=fn_t...,678.0,English,USA,PG,170000000.0,2011.0,16000.0,7.5,1.85,42000
75,Color,Doug Liman,585.0,113.0,218.0,509.0,Lara Pulver,10000.0,100189501.0,Action|Adventure|Sci-Fi,Tom Cruise,Edge of Tomorrow,431620,12652,Noah Taylor,1.0,alien|combat|dying repeatedly|end of the world...,http://www.imdb.com/title/tt1631867/?ref_=fn_t...,741.0,English,USA,PG-13,178000000.0,2014.0,854.0,7.9,2.35,77000
80,Color,Jon Favreau,453.0,124.0,4000.0,4000.0,Scarlett Johansson,21000.0,312057433.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man 2,522371,48638,Jon Favreau,4.0,hammer|military|monaco|revenge|tony stark,http://www.imdb.com/title/tt1228705/?ref_=fn_t...,723.0,English,USA,PG-13,200000000.0,2010.0,19000.0,7.0,2.35,18000
85,Color,Carl Rinsch,218.0,128.0,47.0,982.0,Cary-Hiroyuki Tagawa,18000.0,38297305.0,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,20965,Jin Akanishi,2.0,box office flop|ronin|samurai|shogun|tournament,http://www.imdb.com/title/tt1335975/?ref_=fn_t...,324.0,English,USA,PG-13,175000000.0,2013.0,1000.0,6.3,2.35,35000
90,Color,Rich Moore,377.0,101.0,66.0,833.0,Sarah Silverman,975.0,189412677.0,Adventure|Animation|Comedy|Family|Sci-Fi,Jack McBrayer,Wreck-It Ralph,272534,4451,Joe Lo Truglio,1.0,arcade|candy|glitch|king|medal,http://www.imdb.com/title/tt1772341/?ref_=fn_t...,345.0,English,USA,PG,165000000.0,2012.0,931.0,7.8,2.35,40000
95,Color,James Gunn,653.0,121.0,571.0,3000.0,Vin Diesel,14000.0,333130696.0,Action|Adventure|Sci-Fi,Bradley Cooper,Guardians of the Galaxy,682155,32438,Djimon Hounsou,3.0,bounty hunter|outer space|raccoon|talking anim...,http://www.imdb.com/title/tt2015381/?ref_=fn_t...,1097.0,English,USA,PG-13,170000000.0,2014.0,14000.0,8.1,2.35,96000

# 3. 3주차 과제

## a. 다음 지시대로 빈 코드셀을 작성-->실행하여 캡처화면(jpg, png...)을 제출하세요. 😊
---
1. 다음 url에서 csv 파일을 읽어와 df라는 이름의 데이터프레임으로 만들어 보세요.(url = 'https://raw.githubusercontent.com/tysep16/DV25_1/refs/heads/main/movie.csv')
- *힌트: pd.read_csv()*

In [554]:
df = pd.read_csv('https://raw.githubusercontent.com/tysep16/DV25_1/refs/heads/main/movie.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

2. df의 컬럼 라벨(열 라벨)을 출력해 보세요.
- *힌트: df.columns*

In [555]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

3. 컨프리헨션을 이용하여 컬럼 라벨에 actor가 들어간 컬럼만 출력해 보세요.
- *힌트: df.?[?, ['?' in ? for ? in ?]*

In [556]:
df.loc[:, ['actor' in a for a in df.columns]]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
4911,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
4912,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
4913,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
4914,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
4915,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

4. 감독 중 'James Cameron'이 감독한 영화의 행(row)만 출력해 보세요. (컨프리헨션을 써도 ok, 인덱싱 문법을 써도 ok)
- *힌트: df.?[[이름 == ? for ? in ?], :] 혹은 df[df.? == 이름]*

In [557]:
df.loc[['James Cameron' == a for a in df.director_name], :]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,45223,Gloria Stuart,0.0,artist|love|ship|titanic|wet,http://www.imdb.com/title/tt0120338/?ref_=fn_t...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
285,Color,James Cameron,210.0,153.0,0.0,539.0,Jenette Goldstein,780.0,204843350.0,Action|Sci-Fi,Joe Morton,Terminator 2: Judgment Day,744891,2829,S. Epatha Merkerson,0.0,future|liquid metal|multiple cameos|sexy woman...,http://www.imdb.com/title/tt0103064/?ref_=fn_t...,983.0,English,USA,R,102000000.0,1991.0,604.0,8.5,2.35,13000
288,Color,James Cameron,94.0,141.0,0.0,618.0,Tia Carrere,2000.0,146282411.0,Action|Comedy|Thriller,Jamie Lee Curtis,True Lies,190439,4528,Tom Arnold,0.0,espionage|secret agent|secret mission|spy|spy ...,http://www.imdb.com/title/tt0111503/?ref_=fn_t...,351.0,English,USA,R,115000000.0,1994.0,1000.0,7.2,2.35,0
599,Color,James Cameron,82.0,171.0,0.0,638.0,Todd Graff,2000.0,54222000.0,Adventure|Drama|Sci-Fi|Thriller,Michael Biehn,The Abyss,131217,4074,Mary Elizabeth Mastrantonio,0.0,alien|estranged couple|ocean|submarine|underwater,http://www.imdb.com/title/tt0096754/?ref_=fn_t...,380.0,English,USA,PG-13,69500000.0,1989.0,650.0,7.6,2.35,0
2455,Color,James Cameron,250.0,154.0,0.0,604.0,Carrie Henn,2000.0,85200000.0,Action|Adventure|Sci-Fi,Michael Biehn,Aliens,488537,4228,Jenette Goldstein,1.0,alien|human versus alien|monster|rescue missio...,http://www.imdb.com/title/tt0090605/?ref_=fn_t...,1076.0,English,USA,R,18500000.0,1986.0,626.0,8.4,1.85,18000
3508,Color,James Cameron,204.0,107.0,0.0,255.0,Brian Thompson,2000.0,38400000.0,Action|Sci-Fi,Michael Biehn,The Terminator,600266,3582,Paul Winfield,1.0,cyborg|future war|robot|shootout in a police s...,http://www.imdb.com/title/tt0088247/?ref_=fn_t...,692.0,English,UK,R,6500000.0,1984.0,663.0,8.1,1.85,13000

In [558]:
df[df.director_name == 'James Cameron']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,45223,Gloria Stuart,0.0,artist|love|ship|titanic|wet,http://www.imdb.com/title/tt0120338/?ref_=fn_t...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
285,Color,James Cameron,210.0,153.0,0.0,539.0,Jenette Goldstein,780.0,204843350.0,Action|Sci-Fi,Joe Morton,Terminator 2: Judgment Day,744891,2829,S. Epatha Merkerson,0.0,future|liquid metal|multiple cameos|sexy woman...,http://www.imdb.com/title/tt0103064/?ref_=fn_t...,983.0,English,USA,R,102000000.0,1991.0,604.0,8.5,2.35,13000
288,Color,James Cameron,94.0,141.0,0.0,618.0,Tia Carrere,2000.0,146282411.0,Action|Comedy|Thriller,Jamie Lee Curtis,True Lies,190439,4528,Tom Arnold,0.0,espionage|secret agent|secret mission|spy|spy ...,http://www.imdb.com/title/tt0111503/?ref_=fn_t...,351.0,English,USA,R,115000000.0,1994.0,1000.0,7.2,2.35,0
599,Color,James Cameron,82.0,171.0,0.0,638.0,Todd Graff,2000.0,54222000.0,Adventure|Drama|Sci-Fi|Thriller,Michael Biehn,The Abyss,131217,4074,Mary Elizabeth Mastrantonio,0.0,alien|estranged couple|ocean|submarine|underwater,http://www.imdb.com/title/tt0096754/?ref_=fn_t...,380.0,English,USA,PG-13,69500000.0,1989.0,650.0,7.6,2.35,0
2455,Color,James Cameron,250.0,154.0,0.0,604.0,Carrie Henn,2000.0,85200000.0,Action|Adventure|Sci-Fi,Michael Biehn,Aliens,488537,4228,Jenette Goldstein,1.0,alien|human versus alien|monster|rescue missio...,http://www.imdb.com/title/tt0090605/?ref_=fn_t...,1076.0,English,USA,R,18500000.0,1986.0,626.0,8.4,1.85,18000
3508,Color,James Cameron,204.0,107.0,0.0,255.0,Brian Thompson,2000.0,38400000.0,Action|Sci-Fi,Michael Biehn,The Terminator,600266,3582,Paul Winfield,1.0,cyborg|future war|robot|shootout in a police s...,http://www.imdb.com/title/tt0088247/?ref_=fn_t...,692.0,English,UK,R,6500000.0,1984.0,663.0,8.1,1.85,13000